apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: basic-pipe
  annotations:
    pipelinesascode.tekton.dev/task: "Task.yaml"
spec:
  tasks:
    - name: echo
      taskRef:
        name: success
    
